using System.Text;

namespace Sagas.Core;

/// <summary>
/// A document that will not let you record a result without having first
/// recorded what you expected.
///
/// <see cref="Expect"/> opens a prediction and <see cref="Found"/> closes it;
/// <see cref="Render"/> throws if any prediction is still open. The mechanism is
/// small and its only purpose is to make it impossible to write the report after
/// seeing the numbers, which is the failure mode every performance and
/// correctness write-up has and almost none admit to.
/// </summary>
public sealed class Report
{
    private readonly List<string> _body = [];
    private readonly List<(string Section, bool Held)> _scores = [];
    private string? _open;
    private string _currentSection = "(preamble)";

    public Report(string title, string intro, string generator, string environment)
    {
        Title = title;
        _body.Add($"# {title}");
        _body.Add(string.Empty);
        _body.Add(intro);
        _body.Add(string.Empty);
        _body.Add($"> Generated by `{generator}`. {environment}");
        _body.Add(">");
        _body.Add("> Every claim below is produced by the code in this repository at the moment");
        _body.Add("> this file was written. `dotnet test` fails if the file drifts from the code.");
        _body.Add(string.Empty);
    }

    public string Title { get; }

    public Report H2(string heading)
    {
        RequireClosed($"opening section '{heading}'");
        _currentSection = heading;
        _body.Add(string.Empty);
        _body.Add($"## {heading}");
        _body.Add(string.Empty);
        return this;
    }

    public Report H3(string heading)
    {
        RequireClosed($"opening section '{heading}'");
        _currentSection = heading;
        _body.Add(string.Empty);
        _body.Add($"### {heading}");
        _body.Add(string.Empty);
        return this;
    }

    public Report Para(string text)
    {
        _body.Add(Wrap(text));
        _body.Add(string.Empty);
        return this;
    }

    public Report Note(string text)
    {
        _body.Add(Wrap(text, "> "));
        _body.Add(string.Empty);
        return this;
    }

    public Report Code(string text)
    {
        _body.Add("```");
        _body.AddRange(text.Replace("\r\n", "\n").Split('\n'));
        _body.Add("```");
        _body.Add(string.Empty);
        return this;
    }

    /// <summary>Record what is expected. Must be followed by exactly one <see cref="Found"/>.</summary>
    public Report Expect(string prediction)
    {
        RequireClosed("opening a new prediction");
        _open = prediction;
        _body.Add(Wrap($"**Predicted.** {prediction}"));
        _body.Add(string.Empty);
        return this;
    }

    public Report Found(string result, bool held)
    {
        if (_open is null)
        {
            throw new InvalidOperationException(
                $"Found(...) in section '{_currentSection}' with no matching Expect(...). " +
                "A result without a recorded prediction is a result nobody can be wrong about.");
        }

        _open = null;
        _scores.Add((_currentSection, held));
        _body.Add(Wrap($"**{(held ? "Held" : "Contradicted")}.** {result}"));
        _body.Add(string.Empty);
        return this;
    }

    public Report Table(IReadOnlyList<string> headers, IEnumerable<IReadOnlyList<string>> rows)
    {
        var materialised = rows.Select(r => r.ToArray()).ToList();
        var widths = headers.Select(h => h.Length).ToArray();
        foreach (var row in materialised)
        {
            for (var i = 0; i < widths.Length && i < row.Length; i++)
            {
                widths[i] = Math.Max(widths[i], row[i].Length);
            }
        }

        _body.Add("| " + string.Join(" | ", headers.Select((h, i) => h.PadRight(widths[i]))) + " |");
        _body.Add("| " + string.Join(" | ", widths.Select(w => new string('-', w))) + " |");
        foreach (var row in materialised)
        {
            _body.Add("| " + string.Join(" | ",
                widths.Select((w, i) => (i < row.Length ? row[i] : string.Empty).PadRight(w))) + " |");
        }

        _body.Add(string.Empty);
        return this;
    }

    public string Render()
    {
        RequireClosed("rendering the document");

        var held = _scores.Count(s => s.Held);
        var total = _scores.Count;
        var contradicted = total - held;

        var scoreboard = new List<string>
        {
            string.Empty,
            "## Scoreboard",
            string.Empty,
            Wrap(
                $"{total} predictions were registered before the checker ran. {held} held and " +
                $"{contradicted} were contradicted."),
            string.Empty
        };

        scoreboard.Add("| section | prediction |");
        scoreboard.Add("| ------- | ---------- |");
        foreach (var (section, ok) in _scores)
        {
            scoreboard.Add($"| {section} | {(ok ? "held" : "**contradicted**")} |");
        }

        scoreboard.Add(string.Empty);

        var text = string.Join("\n", _body.Concat(scoreboard)).TrimEnd() + "\n";
        return text.Replace("\r\n", "\n");
    }

    private void RequireClosed(string what)
    {
        if (_open is not null)
        {
            throw new InvalidOperationException(
                $"prediction \"{_open}\" is still open while {what}; every Expect(...) needs its Found(...)");
        }
    }

    private static string Wrap(string text, string prefix = "")
    {
        // Hard-wrapped so the generated file is reviewable in a diff. An
        // 80-column document produces line-level diffs; an unwrapped one
        // produces paragraph-level diffs, and a reviewer stops reading them.
        const int width = 80;
        var words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        var line = new StringBuilder(prefix);
        foreach (var word in words)
        {
            if (line.Length > prefix.Length && line.Length + 1 + word.Length > width)
            {
                sb.AppendLine(line.ToString());
                line = new StringBuilder(prefix);
            }

            if (line.Length > prefix.Length)
            {
                line.Append(' ');
            }

            line.Append(word);
        }

        sb.Append(line);
        return sb.ToString();
    }
}
