// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubscriptionBilling.Infrastructure;

#nullable disable

namespace SubscriptionBilling.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.AuditRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceType", "ResourceId", "OccurredAt");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.CouponEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationCycles")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FixedAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(7, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RedemptionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.CouponRedemptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RedeemedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CouponId", "InvoiceId")
                        .IsUnique();

                    b.ToTable("coupon_redemptions", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.CreditApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppliedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreditId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditId", "InvoiceId")
                        .IsUnique();

                    b.ToTable("credit_applications", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.CreditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OriginalMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("RemainingMinor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "CreatedAt");

                    b.ToTable("credits", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.CreditNoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("credit_notes", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReverseCharge")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TaxExempt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.DunningCaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Escalated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InitialFailureAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethodToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recovered")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("dunning_cases", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.IdempotencyRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Key", "Route")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.InvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreditAppliedMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinalizedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("PeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaxMinor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("SubscriptionId", "PeriodStart", "PeriodEnd", "BillingReason")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.InvoiceLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RevenueRecognizedOverPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Taxable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.MeterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aggregation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RoundingIncrement")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoundingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("meters", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.OutboundWebhookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("outbound_webhooks", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.PaymentAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AttemptedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("payment_attempts", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.PendingChargeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Invoiced")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Taxable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "Invoiced");

                    b.ToTable("pending_charges", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.PlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntervalUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MeterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.PlanVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("EffectiveFrom")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PricingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TaxInclusive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("PlanId", "Version")
                        .IsUnique();

                    b.ToTable("plan_versions", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.SequenceEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("NextValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("sequences", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.SubscriptionChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("NetAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NewPlanVersionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("NewQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OldPlanVersionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OldQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "ChangedAt");

                    b.ToTable("subscription_changes", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnchorDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnchorIsMonthEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AnchorOrigin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouponApplications")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentPeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentPeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAccessSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreviouslyActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateBeforePause")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TrialEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrialEndBehavior")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("CurrentPeriodEnd");

                    b.HasIndex("PlanVersionId");

                    b.HasIndex("CustomerId", "State");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.UsageEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustmentOfEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(20, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RollupPeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RollupPeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueKey")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("AdjustmentOfEventId");

                    b.HasIndex("SubscriptionId", "MeterId", "OccurredAt");

                    b.ToTable("usage_events", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.UsageRollupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AggregateValue")
                        .HasPrecision(20, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("BillableUnits")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEventId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastOccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LastValue")
                        .HasPrecision(20, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(20, 6)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SumValue")
                        .HasPrecision(20, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("UniqueCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "MeterId", "PeriodStart", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("usage_rollups", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.UsageUniqueKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "MeterId", "PeriodStart", "UniqueKey")
                        .IsUnique();

                    b.ToTable("usage_unique_keys", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.WebhookNonceEntity", b =>
                {
                    b.Property<string>("Nonce")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Nonce");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("webhook_nonces", (string)null);
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.InvoiceLineEntity", b =>
                {
                    b.HasOne("SubscriptionBilling.Infrastructure.InvoiceEntity", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.PlanEntity", b =>
                {
                    b.HasOne("SubscriptionBilling.Infrastructure.MeterEntity", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubscriptionBilling.Infrastructure.ProductEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.PlanVersionEntity", b =>
                {
                    b.HasOne("SubscriptionBilling.Infrastructure.PlanEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SubscriptionBilling.Infrastructure.SubscriptionEntity", b =>
                {
                    b.HasOne("SubscriptionBilling.Infrastructure.CouponEntity", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SubscriptionBilling.Infrastructure.CustomerEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubscriptionBilling.Infrastructure.PlanVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
