"""Distractor documents: the 90% of a knowledge base that answers nothing.

A retrieval benchmark built only from documents that contain answers measures
almost nothing, because the top-k of a 40-chunk index is close to the whole
index. Real corpora are mostly near-misses -- pages that use every word of the
query and state no governed value.

These documents are generated by recombining templates under a fixed seed. They
are lexically realistic and syntactically repetitive, which is disclosed in
docs/known-limitations.md.

One invariant matters more than any other here, and is enforced by
``assert_no_leaked_values`` and by a test: **no distractor may contain any
governed value string.** If one did, it would be an unlabelled correct answer,
and every metric in the lab would be biased downwards by an unknown amount --
precisely the defect that motivated generating the corpus from facts in the
first place.
"""

from __future__ import annotations

import random

from .corpus import Document
from .facts import FACTS, TOPICS

_TITLE_HEAD = {
    "retention": ("Reaper", "Lifecycle", "Expiry", "Tombstone", "Compaction"),
    "limits": ("Admission", "Shedding", "Quota", "Backpressure", "Edge"),
    "sla": ("Probe", "Error Budget", "Incident", "Availability", "Status Page"),
    "auth": ("Token", "Claim", "Directory", "Session", "Credential"),
    "storage": ("Object", "Key Service", "Envelope", "Replica", "Checksum"),
    "deploy": ("Promotion", "Canary", "Rollout", "Feature Flag", "Migration"),
    "backup": ("Log Shipping", "Restore", "Replica Lag", "Snapshot", "Failover"),
    "billing": ("Metering", "Aggregation", "Invoice", "Rating", "Reconciliation"),
}

_TITLE_TAIL = (
    "Internals", "Operations Notes", "Design Rationale", "Troubleshooting",
    "Architecture Overview", "Known Issues", "Migration Guide", "Capacity Notes",
)

_SUBJECTS = {
    "retention": ("the reaper", "the tombstone index", "the expiry queue",
                  "the compaction worker", "the lifecycle daemon"),
    "limits": ("the admission controller", "the token bucket", "the shedder",
               "the edge proxy", "the quota cache"),
    "sla": ("the probe fleet", "the error budget tracker", "the incident bot",
            "the status publisher", "the availability rollup"),
    "auth": ("the token service", "the claim resolver", "the directory sync",
             "the session store", "the revocation list"),
    "storage": ("the object writer", "the key service", "the envelope cache",
                "the replica placer", "the checksum verifier"),
    "deploy": ("the promotion ladder", "the canary analyser", "the flag service",
               "the migration runner", "the rollout controller"),
    "backup": ("the log shipper", "the restore harness", "the lag monitor",
               "the snapshot indexer", "the failover arbiter"),
    "billing": ("the meter aggregator", "the rating engine", "the invoice builder",
                "the reconciliation job", "the usage buffer"),
}

_VERB_PHRASES = (
    "is deployed as a stateless service behind the regional load balancer",
    "keeps its working set in memory and checkpoints to local disk",
    "emits one structured event per unit of work, tagged with the tenant",
    "is horizontally partitioned by tenant hash with no cross-partition reads",
    "runs a leader election over the coordination service on startup",
    "degrades to a read-only mode when its dependency is unavailable",
    "batches writes and flushes them on either a size or an age trigger",
    "exposes a health endpoint that reports dependency status individually",
    "is the most common source of paging alerts during a regional failover",
    "was rewritten last year and the previous implementation is still present "
    "behind a flag",
)

_OBSERVATIONS = (
    "Operators should not restart it during a rollout; wait for the ladder to "
    "drain first.",
    "The dashboard for this component is linked from the service catalogue "
    "entry.",
    "Its queue depth is the leading indicator for every failure mode we have "
    "seen.",
    "There is no automated remediation; a human decides whether to intervene.",
    "The most recent incident involving it was caused by a dependency, not by "
    "the component itself.",
    "Its configuration is deployed through the same pipeline as application "
    "code.",
    "A cold start takes noticeably longer than a warm restart and this is "
    "expected.",
    "It does not participate in the request path, so a failure here is not "
    "customer visible immediately.",
)

# Numbers are drawn from this pool, which is disjoint from every governed value.
# Enforced by assert_no_leaked_values and by a test.
_NUMBERS = (
    "512 rows", "3 replicas", "17 shards", "1200 events", "64 KB", "9 workers",
    "250 milliseconds", "2 retries", "48 partitions", "128 connections",
    "6 hours of headroom", "11 concurrent streams", "375 buckets",
)

_TECHNICAL = (
    "The batch size is {n}, chosen empirically and not tuned since.",
    "Internal buffers are sized for {n} before backpressure is applied.",
    "The default fan-out is {n} across the regional fleet.",
    "A single instance holds {n} in its resident set under normal load.",
    "Timeouts inside the component are set to {n} for every downstream call.",
)

_CAVEATS = (
    "None of the figures in this section are contractual and they change "
    "without notice.",
    "This page documents implementation, not policy; see the topic guides for "
    "governed values.",
    "Numbers here describe internal behaviour and are not the limits applied to "
    "customer requests.",
    "Do not quote anything on this page to a customer.",
)

# A long tail. Without it the generated text has ~700 distinct terms over ~18k
# tokens, so almost nothing is rare and inverse document frequency carries
# nearly no information -- which would make every IDF-weighted retriever in the
# lab look identical for reasons that have nothing to do with retrieval. Real
# operational documentation is full of service code names, error constants and
# ticket references, and they are exactly the terms that occur once or twice.
_CODENAMES = (
    "atlas", "borealis", "cinder", "dovetail", "ember", "flint", "granite",
    "harbour", "ironwood", "juniper", "kestrel", "lantern", "marlin", "nimbus",
    "obsidian", "pewter", "quarry", "redwood", "saltmarsh", "tundra", "umber",
    "vellum", "wicker", "xenon", "yarrow", "zephyr", "alder", "basalt",
    "cobalt", "driftwood", "elmwood", "fennel", "gossamer", "hollow",
)

_ERROR_STEMS = (
    "QUEUE_STALL", "LEASE_LOST", "SHARD_SPLIT", "CLOCK_SKEW", "DIGEST_MISMATCH",
    "PARTIAL_FLUSH", "STALE_EPOCH", "BUDGET_EXHAUSTED", "PLACEMENT_DENIED",
    "REPLAY_GAP", "CHECKSUM_DRIFT", "WATERMARK_REGRESSION",
)

_IDENTIFIER_TEMPLATES = (
    "The component is registered in the service catalogue as svc-{cn}-{k}.",
    "Failures of this kind surface as ERR_{err} in the structured logs.",
    "Incident INC-{num} is the canonical example and its writeup is worth "
    "reading before making changes here.",
    "The owning team tracks this under the {cn} workstream.",
    "Configuration lives in the {cn} bundle, version {k}.",
    "A dashboard panel named {cn}-saturation shows the relevant signal.",
    "The alert rule is {cn}_{err}_high and pages the platform rotation.",
)


def _identifier(rng: random.Random) -> str:
    return rng.choice(_IDENTIFIER_TEMPLATES).format(
        cn=rng.choice(_CODENAMES),
        err=rng.choice(_ERROR_STEMS),
        k=rng.randint(2, 41),
        num=rng.randint(1000, 9999),
    )


def _paragraph(rng: random.Random, topic: str) -> str:
    subject = rng.choice(_SUBJECTS[topic])
    parts = [
        f"{subject.capitalize()} {rng.choice(_VERB_PHRASES)}.",
        rng.choice(_TECHNICAL).format(n=rng.choice(_NUMBERS)),
        rng.choice(_OBSERVATIONS),
        _identifier(rng),
    ]
    if rng.random() < 0.35:
        parts.append(rng.choice(_CAVEATS))
    if rng.random() < 0.45:
        parts.append(_identifier(rng))
    rng.shuffle(parts)
    return " ".join(parts)


def build_distractors(count: int = 58, seed: int = 20240517) -> tuple[Document, ...]:
    rng = random.Random(seed)
    docs: list[Document] = []
    for i in range(count):
        topic = TOPICS[i % len(TOPICS)]
        title = (
            f"{rng.choice(_TITLE_HEAD[topic])} {rng.choice(_TITLE_TAIL)}"
        )
        doc_id = f"note-{topic}-{i:02d}"
        lines = [f"# {title}", ""]
        for _ in range(rng.randint(4, 7)):
            lines.append(f"## {rng.choice(_SUBJECTS[topic]).title()}")
            lines.append("")
            for _ in range(rng.randint(2, 4)):
                lines.append(_paragraph(rng, topic))
                lines.append("")
        docs.append(Document(doc_id, title, "distractor", "\n".join(lines)))
    return tuple(docs)


def assert_no_leaked_values(docs: tuple[Document, ...]) -> None:
    """No distractor may state a governed value.

    A distractor containing one would be an unlabelled correct answer. Every
    recall figure in the lab would then be understated by an unknown amount,
    and the understatement would differ per configuration, which is worse than
    a uniform bias because it is not cancelled by comparison.
    """
    values = {f.value for f in FACTS}
    for d in docs:
        for v in values:
            if v in d.text:
                raise AssertionError(
                    f"distractor {d.doc_id} contains governed value {v!r}"
                )
