"""Tokenisation and text utilities shared by every stage of the lab.

One tokeniser for the whole pipeline. If the chunker, the index and the metrics
disagree about what a token is, chunk size limits stop meaning anything and the
comparison between chunkers becomes a comparison between tokenisers.
"""

from __future__ import annotations

import re
import unicodedata
from typing import Iterator

_WORD = re.compile(r"[a-z0-9]+(?:[-'][a-z0-9]+)*")

# Deliberately short. A long stop list silently deletes query terms that carry
# the distinction between two facts ("logs retained *for* 400 days" vs
# "*within* 400 days"), and the deletion is invisible in the metrics.
STOPWORDS = frozenset(
    """a an the of to in on for is are be was were and or as at by with from
    this that these those it its our your we you""".split()
)


def normalise(text: str) -> str:
    """Case-fold and strip accents. Applied identically to documents and queries."""
    folded = unicodedata.normalize("NFKD", text.lower())
    return "".join(c for c in folded if not unicodedata.combining(c))


def tokens_with_offsets(text: str) -> list[tuple[str, int, int]]:
    """Tokens paired with their character offsets in the *original* string.

    Offsets are what make span-level relevance labels possible: a chunk knows
    which characters of the source document it covers, so coverage of a labelled
    answer span is an exact set operation rather than a string search.
    """
    lowered = normalise(text)
    if len(lowered) != len(text):
        # NFKD expanded or contracted something; fall back to per-token
        # normalisation so offsets stay aligned with the original text.
        out: list[tuple[str, int, int]] = []
        for m in re.finditer(r"[A-Za-z0-9]+(?:[-'][A-Za-z0-9]+)*", text):
            out.append((normalise(m.group(0)), m.start(), m.end()))
        return out
    return [(m.group(0), m.start(), m.end()) for m in _WORD.finditer(lowered)]


def tokenize(text: str) -> list[str]:
    return [t for t, _, _ in tokens_with_offsets(text)]


def content_tokens(text: str) -> list[str]:
    return [t for t in tokenize(text) if t not in STOPWORDS]


def stem(token: str) -> str:
    """A deliberately small suffix stripper.

    Not Porter. Porter conflates 'retention'/'retain' but also 'plan'/'plane',
    and every conflation it makes is one the lab can no longer measure. This
    handles the inflections the corpus actually contains and nothing else, so
    that a retrieval failure is a retrieval failure rather than a stemmer
    artefact. See docs/adr/0003-no-porter-stemmer.md.
    """
    for suffix in ("ies", "es", "s"):
        if len(token) > 4 and token.endswith(suffix):
            if suffix == "ies":
                return token[:-3] + "y"
            if suffix == "es" and token[-3] in "sxzo":
                return token[:-2]
            if suffix == "s" and not token.endswith("ss"):
                return token[:-1]
    return token


def analysed(text: str) -> list[str]:
    """Full analysis chain: normalise, tokenise, drop stopwords, stem."""
    return [stem(t) for t in content_tokens(text)]


def ngrams(items: list[str], n: int) -> Iterator[tuple[str, ...]]:
    for i in range(len(items) - n + 1):
        yield tuple(items[i : i + n])


def sentences_with_offsets(text: str) -> list[tuple[int, int]]:
    """Sentence boundaries as (start, end) character offsets.

    Regex sentence splitting is wrong in general. It is adequate here because
    the corpus is generated by this repository and its abbreviation set is
    known and small; the splitter is pinned by a test that asserts it never
    splits inside one of them.
    """
    protected = {"e.g.", "i.e.", "etc.", "vs.", "no.", "approx."}
    spans: list[tuple[int, int]] = []
    start = 0
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if ch in ".!?":
            tail = text[max(0, i - 8) : i + 1].lower()
            if any(tail.endswith(p) for p in protected):
                i += 1
                continue
            j = i + 1
            while j < n and text[j] in '")]':
                j += 1
            if j >= n or text[j].isspace():
                seg = text[start:j]
                if seg.strip():
                    spans.append((start, j))
                while j < n and text[j].isspace():
                    j += 1
                start = j
                i = j
                continue
        if ch == "\n" and i + 1 < n and text[i + 1] == "\n":
            seg = text[start:i]
            if seg.strip():
                spans.append((start, i))
            j = i
            while j < n and text[j].isspace():
                j += 1
            start = j
            i = j
            continue
        i += 1
    if start < n and text[start:].strip():
        spans.append((start, n))
    return spans
