// Command semcache runs the whole experiment and writes the report.
//
// Usage:
//
//	go run ./cmd/semcache            # report to stdout
//	go run ./cmd/semcache -out FILE  # also write markdown to FILE
//
// The report is the deliverable. The code below is a laboratory notebook: each
// section states a prediction, runs one measurement, and records whether the
// prediction survived.
package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strings"

	"semcache/internal/cache"
	"semcache/internal/corpus"
	"semcache/internal/embed"
	"semcache/internal/flight"
	"semcache/internal/gateway"
	"semcache/internal/report"
	"semcache/internal/workload"
)

func main() {
	out := flag.String("out", "", "also write the report to this file")
	flag.Parse()

	sinks := []io.Writer{os.Stdout}
	if *out != "" {
		f, err := os.Create(*out)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		defer f.Close()
		sinks = append(sinks, f)
	}
	w := report.New(sinks...)

	w.Title("Semantic cache and coalescing gateway: results")
	w.Note(
		"Generated by `go run ./cmd/semcache`. Every number below is deterministic:",
		"the corpus is hand-written, the embedding is fitted with a fixed seed, and the",
		"arrival stream comes from a splitmix64 generator with a fixed seed. Re-running",
		"reproduces this file byte for byte.",
	)

	texts := allTexts()
	model := embed.Fit(texts, embed.Lexical, 4096, 192, 0x51E5EED)

	s0(w, model)
	s1(w, model)
	s2(w, model)
	base := s3(w, model)
	s4(w, model, base)
	s5(w, model)
	s6(w, model)
	s7(w)

	w.Section(8, "What this does not show")
	w.Note(
		"See `docs/known-limitations.md`. The three that most affect the numbers above:",
		"the similarity function is a TF-IDF cosine over a hand-authored synonymy table,",
		"not a transformer; the corpus is 170 queries, so tail percentiles are coarse;",
		"and the adversarial intents are boosted 2x in the arrival stream, which inflates",
		"every error rate relative to a benign production stream. The *comparisons* are",
		"unaffected - both arms of every comparison see the same stream - but the absolute",
		"error rates are a worst case, not a forecast.",
	)
}

func allTexts() []string {
	qs := corpus.All()
	out := make([]string, len(qs))
	for i, q := range qs {
		out[i] = q.Text
	}
	return out
}

// --- 0. the instrument ------------------------------------------------------

func s0(w *report.W, m *embed.Model) {
	w.Section(0, "The instrument")
	w.Expect(
		"The corpus should be small enough to have been genuinely hand-labelled and",
		"large enough that the confusable families are not anecdotes. Every intent in a",
		"family must have at least one sibling, or the family is not a trap.",
	)

	qs := corpus.All()
	intents := corpus.Intents()
	fams := map[string][]string{}
	for _, it := range intents {
		if f := corpus.Family(it); f != "" {
			fams[f] = append(fams[f], it)
		}
	}
	shared := 0
	for _, it := range intents {
		if corpus.Shared(it) {
			shared++
		}
	}
	orphans := []string{}
	for f, members := range fams {
		if len(members) < 2 {
			orphans = append(orphans, f)
		}
	}
	sort.Strings(orphans)

	w.Table([]string{"quantity", "value"}, [][]string{
		{"queries", report.N(len(qs))},
		{"intents", report.N(len(intents))},
		{"adversarial queries", report.N(len(corpus.Adversarial()))},
		{"confusable families", report.N(len(fams))},
		{"intents in a family", report.N(countInFamilies(fams))},
		{"tenant-independent intents", report.N(shared)},
		{"tenants", report.N(len(corpus.Tenants()))},
		{"vocabulary (unigrams+bigrams)", report.N(m.VocabSize())},
		{"single-member families (must be 0)", report.N(len(orphans))},
	})

	rows := [][]string{}
	names := make([]string, 0, len(fams))
	for f := range fams {
		names = append(names, f)
	}
	sort.Strings(names)
	for _, f := range names {
		sort.Strings(fams[f])
		rows = append(rows, []string{f, report.N(len(fams[f])), strings.Join(fams[f], ", ")})
	}
	w.Sub("The confusable families")
	w.Note(
		"These are the pairs that a similarity threshold has to separate and a keyword",
		"search does not. They are the whole subject: a cache that gets these wrong",
		"answers a question about Germany with the shipping policy for France.",
	)
	w.Table([]string{"family", "n", "intents"}, rows)

	w.Found(
		"No single-member families. The corpus is", report.N(len(qs)), "queries over",
		report.N(len(intents)), "intents, of which", report.N(countInFamilies(fams)),
		"sit in a designed trap.",
	)
}

func countInFamilies(fams map[string][]string) int {
	n := 0
	for _, v := range fams {
		n += len(v)
	}
	return n
}

// --- 1. the distributions ---------------------------------------------------

type simSets struct{ same, conf, unrel []float64 }

func s1(w *report.W, m *embed.Model) simSets {
	w.Section(1, "The number everybody reports is the number that hides the failure")
	w.Expect(
		"Same-intent pairs should score high, unrelated pairs low. If a threshold",
		"exists that admits paraphrases and rejects everything else, a semantic cache",
		"is safe and this project is over. The prediction under test is that it does",
		"NOT exist - specifically that the confusable population overlaps the",
		"same-intent population so heavily that no cut separates them.",
	)

	qs := corpus.All()
	vecs := make([]embed.Vector, len(qs))
	for i, q := range qs {
		vecs[i] = m.Embed(q.Text)
	}
	var ss simSets
	for i := 0; i < len(qs); i++ {
		for j := i + 1; j < len(qs); j++ {
			s := embed.Cosine(vecs[i], vecs[j])
			switch {
			case qs[i].Intent == qs[j].Intent:
				ss.same = append(ss.same, s)
			case corpus.Confusable(qs[i], qs[j]):
				ss.conf = append(ss.conf, s)
			default:
				ss.unrel = append(ss.unrel, s)
			}
		}
	}

	w.Table(report.DistHeader(), [][]string{
		report.Summarise("same intent (must hit)", append([]float64(nil), ss.same...)).Row(),
		report.Summarise("confusable (must miss)", append([]float64(nil), ss.conf...)).Row(),
		report.Summarise("unrelated (must miss)", append([]float64(nil), ss.unrel...)).Row(),
	})

	w.Sub("What a threshold actually buys")
	w.Note(
		"Read this table as: *if you tune the threshold to keep this much of the",
		"paraphrase traffic, this is the share of each wrong population you also let in.*",
	)
	rows := [][]string{}
	for _, keep := range []float64{0.90, 0.75, 0.50, 0.25, 0.10} {
		thr, admConf := report.Overlap(ss.same, ss.conf, keep)
		_, admUn := report.Overlap(ss.same, ss.unrel, keep)
		rows = append(rows, []string{
			report.Pct(keep), report.F3(thr), report.Pct(admConf), report.Pct2(admUn),
		})
	}
	w.Table([]string{"paraphrase recall", "threshold", "confusable admitted", "unrelated admitted"}, rows)

	w.Sub("The distributions, drawn")
	w.Code("same intent\n" + report.Histogram(ss.same, 0, 1, 20, 40) +
		"\nconfusable\n" + report.Histogram(ss.conf, 0, 1, 20, 40))

	// The composition argument: the aggregate false-hit rate is an average over
	// a population that is 97% trivial.
	total := len(ss.same) + len(ss.conf) + len(ss.unrel)
	w.Found(
		"No threshold separates paraphrase from confusable: at every operating point",
		"the confusable admission rate is one to two orders of magnitude above the",
		"unrelated admission rate. And the confusable population is only",
		report.Pct2(float64(len(ss.conf))/float64(total)), "of all pairs, against",
		report.Pct(float64(len(ss.unrel))/float64(total)), "unrelated. **An aggregate",
		"false-hit rate is therefore a weighted average that is",
		report.Pct(float64(len(ss.unrel))/float64(total)),
		"composed of the easy case.** It will look excellent while the cache is wrong",
		"about every question a user could plausibly confuse.",
	)
	return ss
}

// --- 2. the structural bound ------------------------------------------------

func s2(w *report.W, m *embed.Model) {
	w.Section(2, "Why this is not an embedding problem")
	w.Expect(
		"The failure above looks like a weak encoder. It is not; it is arithmetic.",
		"For L2-normalised pooled vectors the cosine is the shared mass: if two texts",
		"differ in a feature set D, the similarity drop is the share of the vector's",
		"squared weight carried by D. So swapping *germany* for *france* costs exactly",
		"what *germany* is worth in that sentence, and no more. **Two predictions:**",
		"(a) the measured drop tracks the differing-feature mass share closely, and",
		"(b) because a paraphrase rewrites more of the sentence than a decisive swap",
		"does, the most similar confusable pairs will score ABOVE a large share of the",
		"genuine paraphrases. If (b) holds, no threshold can work, and that is a",
		"theorem about pooling rather than a complaint about TF-IDF.",
	)

	byIntent := map[string][]corpus.Query{}
	for _, q := range corpus.All() {
		byIntent[q.Intent] = append(byIntent[q.Intent], q)
	}
	intents := corpus.Intents()

	type row struct {
		a, b      string
		diff      []string
		predicted float64
		measured  float64
	}
	var rows []row
	for _, ia := range intents {
		for _, ib := range intents {
			if ia >= ib || corpus.Family(ia) == "" || corpus.Family(ia) != corpus.Family(ib) {
				continue
			}
			bestSim, bestA, bestB := -1.0, "", ""
			for _, qa := range byIntent[ia] {
				for _, qb := range byIntent[ib] {
					s := embed.Cosine(m.Embed(qa.Text), m.Embed(qb.Text))
					if s > bestSim {
						bestSim, bestA, bestB = s, qa.Text, qb.Text
					}
				}
			}
			if bestA == "" {
				continue
			}
			diff, pred := massBound(m, bestA, bestB)
			rows = append(rows, row{bestA, bestB, diff, pred, 1 - bestSim})
		}
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].measured < rows[j].measured })

	within, sumErr := 0, 0.0
	for _, r := range rows {
		if r.measured <= r.predicted+1e-9 {
			within++
		}
		sumErr += math.Abs(r.measured - r.predicted)
	}

	tbl := [][]string{}
	for _, r := range rows[:min(12, len(rows))] {
		tbl = append(tbl, []string{
			trunc(r.a, 32), trunc(r.b, 32), trunc(strings.Join(r.diff, " "), 30),
			report.F3(r.predicted), report.F3(r.measured),
		})
	}
	w.Note("The twelve closest confusable pairs, i.e. the twelve most dangerous:")
	w.Table([]string{"query A", "query B", "differing features",
		"predicted drop (mass share)", "measured drop"}, tbl)

	w.Found("(a)",
		"The bound holds in", report.N(within), "of", report.N(len(rows)),
		"cases ("+report.Pct(float64(within)/float64(len(rows)))+"),",
		"mean absolute error", report.F3(sumErr/float64(len(rows)))+".",
		"Note what the differing-feature column shows: swapping one WORD changes",
		"several FEATURES, because the bigrams containing it change too. The first",
		"version of this section predicted the drop from a single token's share and",
		"was wrong on 32 of 35 pairs; the error was in the prediction, not the code.",
	)

	// (b) the crux: are the worst confusables more similar than typical paraphrases?
	var same, conf []float64
	qs := corpus.All()
	vecs := make([]embed.Vector, len(qs))
	for i, q := range qs {
		vecs[i] = m.Embed(q.Text)
	}
	for i := 0; i < len(qs); i++ {
		for j := i + 1; j < len(qs); j++ {
			s := embed.Cosine(vecs[i], vecs[j])
			if qs[i].Intent == qs[j].Intent {
				same = append(same, s)
			} else if corpus.Confusable(qs[i], qs[j]) {
				conf = append(conf, s)
			}
		}
	}
	confP90 := report.Percentile(append([]float64(nil), conf...), 0.90)
	below := 0
	for _, s := range same {
		if s < confP90 {
			below++
		}
	}
	w.Sub("The crux")
	w.Table([]string{"quantity", "value"}, [][]string{
		{"90th percentile of CONFUSABLE similarity", report.F3(confP90)},
		{"paraphrase pairs scoring BELOW it", report.N(below) + " of " + report.N(len(same))},
		{"i.e. share of genuine paraphrases a threshold set to reject the worst 10% of traps would also reject",
			report.Pct(float64(below) / float64(len(same)))},
	})
	w.Found("(b)",
		"A threshold high enough to reject the top decile of confusable pairs throws",
		"away", report.Pct(float64(below)/float64(len(same))), "of genuine paraphrases.",
		"**The orderings interleave, so the populations are not separable by any cut of",
		"this score.** That is not a defect of TF-IDF. Any encoder that reduces a",
		"sentence to one vector spends its capacity on the sentence's bulk, and the",
		"decisive word is not the bulk. A better encoder changes the numbers; it does",
		"not change the shape. The fix has to live outside the similarity function.",
	)
}

// massBound returns the features present in exactly one of the two texts and
// the similarity drop implied by their share of the vectors' squared weight.
//
// For unit vectors, cos = <a,b> = sum over SHARED features of a_i*b_i. When the
// shared features carry near-identical weight in both texts - which is what
// "the same sentence with one word swapped" means - that sum is approximately
// the shared mass, so the drop is approximately the differing mass.
func massBound(m *embed.Model, a, b string) ([]string, float64) {
	wa, wb := m.TokenWeights(a), m.TokenWeights(b)

	// Accumulate in sorted key order. Ranging over a Go map is deliberately
	// randomised, and floating-point addition is not associative, so summing
	// in map order makes the result vary in the last bits between runs. The
	// report claims to reproduce byte for byte; a reproducibility check in
	// test.ps1 caught this as a "0.000" that alternated with "-0.000".
	keys := make([]string, 0, len(wa))
	for t := range wa {
		keys = append(keys, t)
	}
	sort.Strings(keys)

	var diff []string
	shared := 0.0
	for _, t := range keys {
		if sb, in := wb[t]; in {
			shared += math.Sqrt(wa[t] * sb)
			continue
		}
		diff = append(diff, t)
	}
	for t := range wb {
		if _, in := wa[t]; !in {
			diff = append(diff, t)
		}
	}
	sort.Strings(diff)
	return diff, 1 - shared
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func trunc(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "\u2026"
}

// --- 3. the baseline --------------------------------------------------------

type baseline struct {
	trap   []gateway.Request
	benign []gateway.Request
	sum    workload.Summary
}

func s3(w *report.W, m *embed.Model) baseline {
	w.Section(3, "The aggregate false-hit rate measures your traffic, not your cache")
	w.Expect(
		"Exact matching should hit often - 4000 requests over 163 surface forms - and",
		"be incapable of a wrong answer. Semantic matching should hit more. The",
		"prediction is the one from section 1, stated operationally: **hold the cache",
		"configuration fixed and change only the traffic mix, and the headline",
		"false-hit rate will move a lot while the per-subset error rates barely move.**",
		"If that happens, the aggregate is a property of the workload and cannot be",
		"used to accept or reject a cache.",
	)

	trapCfg := workload.Default()
	trap := workload.Generate(trapCfg)
	benignCfg := trapCfg
	benignCfg.AdversarialBoost = 1.0
	benignCfg.SiblingRate = 0
	benignCfg.OneIntentPerFamily = true
	benign := workload.Generate(benignCfg)

	sum := workload.Describe(trap, trapCfg.BurstSpreadUs)
	bsum := workload.Describe(benign, benignCfg.BurstSpreadUs)

	w.Sub("The two arrival streams")
	w.Note(
		"Same generator, same seed, same corpus, same size, same burst structure. The",
		"only difference is that the benign stream's users never ask about two members",
		"of the same confusable family - they ask about Germany but not France, about",
		"the free tier but not the pro tier. The traps are still in the corpus and still",
		"in the cache's reach. Nobody walks into them.",
	)
	w.Table([]string{"property", "trap-heavy", "benign"}, [][]string{
		{"requests", report.N(sum.N), report.N(bsum.N)},
		{"distinct intents", report.N(sum.DistinctIntents), report.N(bsum.DistinctIntents)},
		{"distinct surface forms", report.N(sum.DistinctTexts), report.N(bsum.DistinctTexts)},
		{"most popular intent's share", report.Pct(sum.TopIntentShare), report.Pct(bsum.TopIntentShare)},
		{"adversarial share", report.Pct(sum.AdversarialShare), report.Pct(bsum.AdversarialShare)},
		{"peak arrivals in one 40ms window", report.N(sum.MaxOverlap), report.N(bsum.MaxOverlap)},
	})

	w.Sub("Policies, on the trap-heavy stream")
	var arms []armResult
	rows := [][]string{}
	for _, a := range []struct {
		name string
		cfg  gateway.Config
	}{
		{"exact only", exactCfg()},
		{"semantic 0.75", armCfg(0.75, false, gateway.CoalesceOff)},
		{"semantic 0.60", armCfg(0.60, false, gateway.CoalesceOff)},
		{"semantic 0.45", armCfg(0.45, false, gateway.CoalesceOff)},
	} {
		r := runArm(a.name, a.cfg, m, trap)
		arms = append(arms, r)
		rows = append(rows, r.row())
	}
	w.Table(armHeader(), rows)

	w.Sub("The same configuration on both streams, plus a fixed probe")
	w.Note(
		"The last column is not a traffic measurement at all. The trap probe warms a",
		"cache with one entry per intent and then asks, for every confusable pair in",
		"the corpus, whether the cache would serve one from the other. It depends only",
		"on the threshold, the guard and the encoder - never on who happened to call",
		"today.",
	)
	cmp := [][]string{}
	var pair []armResult
	for _, s := range []struct {
		name string
		reqs []gateway.Request
	}{{"benign", benign}, {"trap-heavy", trap}} {
		cfg := armCfg(0.60, false, gateway.CoalesceOff)
		r := runArm(s.name, cfg, m, s.reqs)
		pair = append(pair, r)
		hit, tot := trapProbe(m, cfg)
		cmp = append(cmp, []string{
			s.name, report.Pct(r.st.HitRate()), report.Pct2(r.falseRate()),
			report.Pct(r.st.Precision()),
			fmt.Sprintf("%d/%d = %s", hit, tot, report.Pct(float64(hit)/float64(tot))),
		})
	}
	w.Table([]string{"stream", "hit rate", "false-hit rate (headline)", "precision",
		"trap probe (config-only)"}, cmp)

	probeHit, probeTot := trapProbe(m, armCfg(0.60, false, gateway.CoalesceOff))
	w.Sub("The probe responds to the configuration, which is the point")
	prows := [][]string{}
	for _, thr := range []float64{0.85, 0.75, 0.60, 0.45, 0.30} {
		h, t := trapProbe(m, armCfg(thr, false, gateway.CoalesceOff))
		prows = append(prows, []string{report.F3(thr),
			fmt.Sprintf("%d/%d", h, t), report.Pct(float64(h) / float64(t))})
	}
	w.Table([]string{"threshold", "confused pairs", "trap rate"}, prows)

	w.Found(
		"Identical cache, identical threshold, identical corpus, identical code. The",
		"headline false-hit rate reads", report.Pct2(pair[0].falseRate()),
		"on the benign stream and", report.Pct2(pair[1].falseRate()), "on the",
		"trap-heavy one, with no change to the system whatsoever.",
		"**An acceptance threshold written against that number passes on Monday's",
		"traffic and fails on Tuesday's, and the on-call engineer has no code change to",
		"look at.** The probe, meanwhile, reports", report.N(probeHit), "of",
		report.N(probeTot), "confusable pairs are confusable *by this configuration* -",
		"the same answer on both streams, because it does not depend on the stream -",
		"while moving the threshold moves it monotonically. On the trap-heavy stream",
		"every one of the", report.N(pair[1].st.Wrong()), "wrong answers is a",
		"confusable pair.",
		"**Measure a semantic cache with a fixed adversarial probe set, not with",
		"production error rates. The probe regresses when you change the threshold;",
		"the headline regresses when marketing runs a campaign.**",
	)
	return baseline{trap: trap, benign: benign, sum: sum}
}

// trapProbe measures a configuration, not a workload.
//
// It warms a cache with exactly one entry per intent, then replays every OTHER
// phrasing of every intent and counts the confusable pairs the cache would
// actually confuse. Nothing about it depends on arrival order, popularity or
// traffic mix, so it is comparable across releases - which is precisely what a
// production-traffic error rate is not.
func trapProbe(m *embed.Model, cfg gateway.Config) (confused, total int) {
	byIntent := map[string][]corpus.Query{}
	for _, q := range corpus.All() {
		byIntent[q.Intent] = append(byIntent[q.Intent], q)
	}
	intents := corpus.Intents()

	c := cache.New(m, cfg.Cache)
	for _, it := range intents {
		q := byIntent[it][0]
		c.Put(cache.Entry{Text: q.Text, Tenant: q.Tenant, Intent: it, Answer: corpus.Answer(it)})
	}
	for _, it := range intents {
		if corpus.Family(it) == "" {
			continue
		}
		for _, q := range byIntent[it][1:] {
			total++
			if r := c.Lookup(q.Text, q.Tenant); r.Hit && r.Entry.Intent != it {
				confused++
			}
		}
	}
	return confused, total
}

func exactCfg() gateway.Config {
	c := gateway.DefaultConfig()
	c.Cache.ExactOnly = true
	c.Coalesce = gateway.CoalesceOff
	return c
}

func armCfg(thr float64, guard bool, mode gateway.Mode) gateway.Config {
	c := gateway.DefaultConfig()
	c.Cache.Threshold = thr
	c.Cache.Guard = guard
	c.Coalesce = mode
	return c
}

type armResult struct {
	name string
	st   gateway.Stats
	outs []gateway.Outcome
}

func runArm(name string, cfg gateway.Config, m *embed.Model, reqs []gateway.Request) armResult {
	g := gateway.New(cfg, m)
	outs := g.Run(reqs)
	return armResult{name: name, st: g.Stats(), outs: outs}
}

func (a armResult) falseRate() float64 {
	if a.st.Hits() == 0 {
		return 0
	}
	return float64(a.st.Wrong()) / float64(a.st.Hits())
}

// confusableErrRate is the error rate restricted to hits whose served intent
// shares a family with the true one, i.e. the population that matters.
func (a armResult) confusableErrRate() float64 {
	hits, wrong := 0, 0
	for _, o := range a.outs {
		if o.Kind == gateway.KindBackend {
			continue
		}
		if corpus.Family(o.TrueIntent) == "" {
			continue
		}
		hits++
		if !o.Correct {
			wrong++
		}
	}
	if hits == 0 {
		return 0
	}
	return float64(wrong) / float64(hits)
}

func (a armResult) row() []string {
	return []string{
		a.name,
		report.Pct(a.st.HitRate()),
		report.N(a.st.Backend),
		report.Pct2(a.falseRate()),
		report.Pct(a.confusableErrRate()),
		report.Pct(a.st.Precision()),
		report.N(a.st.Entries),
	}
}

func armHeader() []string {
	return []string{"policy", "hit rate", "backend calls", "false-hit rate (all)",
		"error rate (confusable only)", "precision", "entries"}
}

func ratio(a, b float64) float64 {
	if b == 0 {
		return 0
	}
	return a / b
}

func max1(n int) int {
	if n < 1 {
		return 1
	}
	return n
}

// --- 4. the guard -----------------------------------------------------------

func s4(w *report.W, m *embed.Model, base baseline) {
	w.Section(4, "The fix: a veto that lives outside the similarity function")
	w.Expect(
		"Section 2 says a decisive token cannot dominate a pooled vector, so stop",
		"asking it to. Extract each query's decisive tokens and veto a hit when they",
		"disagree, regardless of cosine. The obvious definition of decisive is",
		"*high IDF*. The prediction was that an IDF cut would work. **It does not, and",
		"the reason is worth more than the fix.**",
	)

	w.Sub("Why an IDF cut cannot work here")
	hist := m.IDFHistogram()
	total := 0
	for _, n := range hist {
		total += n
	}
	rows := [][]string{}
	cum := 0
	for df := 1; df < len(hist) && df <= 8; df++ {
		cum += hist[df]
		rows = append(rows, []string{report.N(df), report.N(hist[df]),
			report.Pct(float64(hist[df]) / float64(total)),
			report.Pct(float64(cum) / float64(total))})
	}
	w.Table([]string{"document frequency", "vocabulary entries", "share", "cumulative"}, rows)
	pcts := [][]string{}
	for _, p := range []float64{0.10, 0.30, 0.50, 0.70, 0.90} {
		pcts = append(pcts, []string{report.Pct(p), report.F3(m.IDFPercentile(p))})
	}
	w.Table([]string{"IDF percentile", "value"}, pcts)
	w.Note(
		"Over 170 documents most of the vocabulary occurs once or twice, so the IDF",
		"distribution is a spike. Every percentile from the 10th to the 90th returns",
		"the same cut, which means *there is no IDF threshold to tune*: any setting",
		"admits nearly every content word - `but`, `cannot`, `answer` alongside",
		"`germany` and `401`. The decisive set then grows with sentence length, which",
		"reintroduces exactly the dilution the guard was built to escape. This is a",
		"corpus-size artefact, and it is also what every team hits when they compute",
		"IDF over their own small document set instead of a background corpus.",
	)

	w.Sub("Bound the size of the set instead")
	w.Note(
		"Take the K highest-IDF tokens of each query, however common they are. K is a",
		"budget, not a threshold, so it is insensitive to the shape of the IDF",
		"distribution and to sentence length. Two queries about different countries",
		"cannot agree on their top-K; two phrasings of the same question usually can.",
	)
	sweep := [][]string{}
	type cand struct {
		k     int
		j     float64
		res   armResult
		score float64
	}
	var best cand
	best.score = -1
	for _, k := range []int{1, 2, 3, 4} {
		for _, j := range []float64{0.34, 0.50, 0.67, 1.00} {
			cfg := armCfg(0.60, true, gateway.CoalesceOff)
			cfg.Cache.GuardTopK = k
			cfg.Cache.GuardJaccard = j
			r := runArm(fmt.Sprintf("K=%d J=%.2f", k, j), cfg, m, base.trap)
			sweep = append(sweep, []string{
				report.N(k), report.F3(j),
				report.Pct(r.st.HitRate()),
				report.Pct2(r.falseRate()),
				report.Pct(r.confusableErrRate()),
				report.N(r.st.GuardVetoes),
				report.N(r.st.Hits() - r.st.Wrong()),
			})
			// Correct answers served without a backend call: the quantity an
			// operator is actually buying. It refuses to let a policy win by
			// vetoing everything, and it refuses to let one win by serving
			// everything.
			score := float64(r.st.Hits() - r.st.Wrong())
			if score > best.score {
				best = cand{k, j, r, score}
			}
		}
	}
	w.Table([]string{"top-K", "min Jaccard", "hit rate", "false-hit (headline)",
		"error (confusable)", "vetoes", "correct answers served from cache"}, sweep)

	noGuard := runArm("no guard", armCfg(0.60, false, gateway.CoalesceOff), m, base.trap)
	w.Sub("Head to head at the same threshold, trap-heavy stream")
	w.Table(armHeader(), [][]string{noGuard.row(), best.res.row()})

	w.Sub("What the guard actually vetoed")
	w.Table([]string{"example query", "top-K decisive tokens"},
		guardExamples(m, best.k))

	w.Found(
		"The best setting is K="+report.N(best.k), "with Jaccard",
		report.F3(best.j)+". It takes the confusable error rate from",
		report.Pct(noGuard.confusableErrRate()), "to", report.Pct(best.res.confusableErrRate()),
		"and precision from", report.Pct(noGuard.st.Precision()), "to",
		report.Pct(best.res.st.Precision())+",",
		"while the hit rate moves from", report.Pct(noGuard.st.HitRate()), "to",
		report.Pct(best.res.st.HitRate())+".",
		"In absolute terms it serves", report.N(best.res.st.Hits()-best.res.st.Wrong()-(noGuard.st.Hits()-noGuard.st.Wrong())),
		"more CORRECT answers from cache than the unguarded configuration, which is the",
		"only comparison that is not gameable by moving the threshold.",
		"**The mechanism is not better similarity. It is a second signal that is",
		"insensitive to length, applied as a veto rather than as a term in an average.**",
		"That is the transferable idea: when one feature must be able to overrule a",
		"whole document, it cannot live inside a mean.",
	)

	guardPrice(w, m, noGuard, best.res, best.k, best.j)
}

// guardPrice is the section I did not plan to write.
//
// The sweep above prices the guard at about one point of hit rate, which reads
// as almost free. Writing the unit test for the guard produced a flatly
// contradictory number - it rejected most genuine paraphrases - and both
// measurements were correct. Reconciling them is the most useful thing in this
// report, because the reconciliation is the same error section 3 is about,
// committed a second time against the fix instead of the problem.
func guardPrice(w *report.W, m *embed.Model, noGuard, guarded armResult, k int, j float64) {
	w.Sub("The price the aggregate number hides")

	w.Expect(
		"A one-point drop in hit rate implies the veto almost never fires on traffic",
		"the cache would otherwise have served correctly. Prediction: measuring the",
		"veto directly on the population it exists to adjudicate - pairs of DIFFERENT",
		"wordings of the SAME question - will show a similarly small effect.",
		"**This prediction is wrong, and the aggregate is the reason.**",
	)

	ex, sem := noGuard.st.ExactHits, noGuard.st.SemanticHits
	w.Table([]string{"unguarded arm", "count", "share of hits"}, [][]string{
		{"verbatim repeats (exact key)", report.N(ex), report.Pct(ratio(float64(ex), float64(ex+sem)))},
		{"cross-wording (semantic)", report.N(sem), report.Pct(ratio(float64(sem), float64(ex+sem)))},
	})

	para, conf := populations()
	w.Line(fmt.Sprintf("Held-out populations from the labelled corpus: **%d paraphrase pairs** "+
		"(same intent, different wording - the cache MUST serve these) and **%d confusable "+
		"pairs** (same family, different intent - the cache MUST NOT). Each row stores the "+
		"first query and asks the second, so the guard is the only thing that varies.",
		len(para), len(conf)))
	w.Blank()

	type row struct {
		label      string
		kept, srvd float64
	}
	var rows []row
	rows = append(rows, row{"no guard", pairHitRate(m, armCfg(0.35, false, gateway.CoalesceOff).Cache, para),
		pairHitRate(m, armCfg(0.35, false, gateway.CoalesceOff).Cache, conf)})
	for _, kk := range []int{1, 2, 3, 4} {
		for _, jj := range []float64{0.20, 0.34, 0.50, 0.67, 1.00} {
			c := armCfg(0.35, true, gateway.CoalesceOff).Cache
			c.GuardTopK, c.GuardJaccard = kk, jj
			rows = append(rows, row{fmt.Sprintf("K=%d J=%.2f", kk, jj),
				pairHitRate(m, c, para), pairHitRate(m, c, conf)})
		}
	}
	var tbl [][]string
	for _, r := range rows {
		tbl = append(tbl, []string{r.label, report.Pct(r.kept), report.Pct(r.srvd)})
	}
	w.Table([]string{"guard", "paraphrases KEPT (want high)", "confusables SERVED (want low)"}, tbl)

	var base, chosen row
	for _, r := range rows {
		if r.label == "no guard" {
			base = r
		}
		if r.label == fmt.Sprintf("K=%d J=%.2f", k, j) {
			chosen = r
		}
	}
	lost := ratio(base.kept-chosen.kept, base.kept)

	w.Found(
		"On the population it actually adjudicates, the chosen guard rejects",
		report.Pct(lost), "of the genuine paraphrase hits it could have served",
		"("+report.Pct(base.kept), "kept without it,", report.Pct(chosen.kept), "with it),",
		"while taking confusables served from", report.Pct(base.srvd), "to",
		report.Pct(chosen.srvd)+".",
		"Both numbers are true. The aggregate hit rate barely moves because",
		report.Pct(ratio(float64(ex), float64(ex+sem))), "of cache hits in this workload are",
		"**verbatim repeats**, whose decisive sets are identical by construction and which",
		"the veto therefore passes for free. The guard is nearly invisible in aggregate",
		"precisely because it only touches the minority of traffic that the word",
		"*semantic* refers to.",
	)
	w.Note(
		"So the honest recommendation is narrower than the sweep suggests. If the value",
		"case for the cache is deduplicating repeated identical questions, the veto is",
		"close to free and should be on. If the value case is consolidating paraphrases -",
		"the reason anyone builds a semantic cache rather than a hash map - the veto",
		"removes roughly four out of five of the hits being paid for, and the aggregate",
		"dashboard will not show it. This is section 3's error committed against the fix:",
		"a number dominated by benign traffic, quoted as if it described the hard case.",
	)
	w.Note(
		"Two structural notes visible in the table. At K=1 the Jaccard parameter is inert:",
		"one token gives a Jaccard of 0 or 1, so every setting in (0,1] decides",
		"identically. And J does not mean the same thing at different K, because the",
		"union grows with K - which is why the sweep is not monotone in K at fixed J.",
		"The parameter with a stable meaning is *how many of the K tokens must agree*,",
		"not the ratio.",
	)
}

// populations splits the labelled corpus into the two sets the guard is a
// classifier over. Ground truth is used HERE, in the scoring, and never inside
// the cache - which is what internal/cache's scrambled-label test enforces.
func populations() (para, conf [][2]corpus.Query) {
	byIntent := map[string][]corpus.Query{}
	for _, q := range corpus.All() {
		byIntent[q.Intent] = append(byIntent[q.Intent], q)
	}
	for _, intent := range corpus.Intents() {
		qs := byIntent[intent]
		for i := 0; i+1 < len(qs); i++ {
			if qs[i].Tenant == qs[i+1].Tenant {
				para = append(para, [2]corpus.Query{qs[i], qs[i+1]})
			}
		}
	}
	all := corpus.All()
	for i, a := range all {
		for _, b := range all[i+1:] {
			if a.Tenant == b.Tenant && a.Intent != b.Intent &&
				corpus.ConfusableIntents(a.Intent, b.Intent) {
				conf = append(conf, [2]corpus.Query{a, b})
			}
		}
	}
	return para, conf
}

// pairHitRate stores the first query of each pair in a fresh cache and asks the
// second, so the only variable is the admission policy.
func pairHitRate(m *embed.Model, cfg cache.Config, pairs [][2]corpus.Query) float64 {
	hit := 0
	for _, p := range pairs {
		c := cache.New(m, cfg)
		e := cache.Entry{
			Text: p[0].Text, Tenant: p[0].Tenant, Intent: p[0].Intent,
			Answer: corpus.Answer(p[0].Intent), Vec: m.Embed(p[0].Text),
			Rare: c.DecisiveTokens(p[0].Text),
		}
		c.Put(e)
		if c.Lookup(p[1].Text, p[1].Tenant).Hit {
			hit++
		}
	}
	return ratio(float64(hit), float64(len(pairs)))
}

// guardExamples shows the guard's view of a few designed traps, so the reader
// can see the mechanism rather than trust the aggregate.
func guardExamples(m *embed.Model, k int) [][]string {
	want := []string{
		"how long does shipping take to Germany",
		"how long does shipping take to France",
		"how many requests do I get on free",
		"how many requests do I get on pro",
		"disable 2FA on my account",
		"enable 2FA on my account",
	}
	rows := [][]string{}
	for _, t := range want {
		rows = append(rows, []string{t, strings.Join(m.TopIDFTokens(t, k), ", ")})
	}
	return rows
}

// --- 5. tenancy -------------------------------------------------------------

func s5(w *report.W, m *embed.Model) {
	w.Section(5, "Tenant scoping is not free, and the bill is worth paying")
	w.Expect(
		"Twenty of the intents are platform-wide - status, policy, protocol - and their",
		"answer is the same for every customer, so an unscoped cache reuses them across",
		"tenants and gets a higher hit rate. The other intents are the customer's own",
		"contract. Three intents are worded IDENTICALLY across three tenants and have",
		"three different answers; no similarity function can separate them, because they",
		"are not semantically different. The prediction: unscoped wins on hit rate and",
		"leaks; scoped loses hit rate and cannot leak.",
	)

	wcfg := workload.Default()
	reqs := workload.Generate(wcfg)

	rows := [][]string{}
	var arms []armResult
	for _, scoped := range []bool{false, true} {
		cfg := armCfg(0.60, false, gateway.CoalesceOff)
		cfg.Cache.ScopeByTenant = scoped
		r := runArm(map[bool]string{false: "unscoped", true: "scoped by tenant"}[scoped], cfg, m, reqs)
		arms = append(arms, r)
		leaks, famLeaks := crossTenantLeaks(r.outs, reqs)
		rows = append(rows, []string{
			r.name, report.Pct(r.st.HitRate()), report.N(r.st.Entries),
			report.Pct2(r.falseRate()), report.N(leaks), report.N(famLeaks),
		})
	}
	w.Table([]string{"policy", "hit rate", "entries", "false-hit rate",
		"wrong answers on tenant-specific intents", "of which the identical-wording trap"}, rows)

	w.Found(
		"Scoping costs", report.Pct(arms[0].st.HitRate()-arms[1].st.HitRate()),
		"of hit rate and", report.N(arms[1].st.Entries-arms[0].st.Entries),
		"extra entries, because every platform-wide answer is now cached once per tenant.",
		"It is still the only correct default. The identical-wording trap is the proof:",
		"three tenants ask *\"what is my monthly api request limit\"* in the same words",
		"and need three different answers. There is no threshold, no guard and no",
		"encoder that separates byte-identical strings. **Isolation has to be structural,",
		"because it is the one property similarity cannot express.**",
	)
}

// crossTenantLeaks counts wrong answers on tenant-specific intents, and how
// many of those are the designed identical-wording trap.
func crossTenantLeaks(outs []gateway.Outcome, reqs []gateway.Request) (int, int) {
	leaks, trap := 0, 0
	for _, o := range outs {
		if o.Correct || corpus.Shared(o.TrueIntent) {
			continue
		}
		leaks++
		if corpus.Family(o.TrueIntent) == "tenant-plan" {
			trap++
		}
	}
	return leaks, trap
}

// --- 6. coalescing ----------------------------------------------------------

func s6(w *report.W, m *embed.Model) {
	w.Section(6, "The wrong answer your cache metrics cannot see")
	w.Expect(
		"Coalescing merges concurrent duplicate requests into one backend call. Merging",
		"on identical text is safe. Merging on SIMILARITY is a semantic cache hit under",
		"a different name - except that the cache is never asked, so when it serves the",
		"wrong answer, no cache counter moves. The prediction: semantic coalescing raises",
		"the hit rate, produces wrong answers, and leaves cache-reported precision",
		"untouched.",
	)

	reqs := workload.Generate(workload.Default())
	rows := [][]string{}
	var arms []armResult
	for _, a := range []struct {
		name   string
		mode   gateway.Mode
		poison bool
	}{
		{"no coalescing", gateway.CoalesceOff, false},
		{"exact coalescing", gateway.CoalesceExact, false},
		{"semantic coalescing", gateway.CoalesceSemantic, false},
		{"semantic + cache the result", gateway.CoalesceSemantic, true},
	} {
		cfg := armCfg(0.60, false, a.mode)
		cfg.CoalesceThreshold = 0.60
		cfg.CacheCoalescedResults = a.poison
		r := runArm(a.name, cfg, m, reqs)
		arms = append(arms, r)
		rows = append(rows, []string{
			a.name,
			report.Pct(r.st.HitRate()),
			report.N(r.st.Backend),
			report.N(r.st.Coalesced),
			report.N(r.st.CacheFalse),
			report.N(r.st.CoalescedWrong),
			report.N(r.st.Poisoned),
			report.Pct(r.st.CacheReportedPrecision()),
			report.Pct(r.st.Precision()),
		})
	}
	w.Table([]string{"policy", "hit rate", "backend calls", "coalesced",
		"cache false hits", "coalesced wrong", "poisoned entries",
		"precision AS REPORTED BY THE CACHE", "true precision"}, rows)

	sem := arms[2]
	w.Sub("The knob operators actually turn")
	w.Note(
		"The cache threshold is scrutinised because everyone knows a cache can serve a",
		"stale or wrong answer. The coalescing threshold is not, because coalescing is",
		"filed under *performance*. The reasoning goes: it is one request, it is",
		"in-flight anyway, and merging saves a whole backend call - so set it loose.",
		"Here is that reasoning, priced. The cache configuration is fixed at 0.60",
		"throughout; only the coalescing threshold moves.",
	)
	crows := [][]string{}
	for _, ct := range []float64{0.80, 0.70, 0.60, 0.50, 0.40, 0.30} {
		cfg := armCfg(0.60, false, gateway.CoalesceSemantic)
		cfg.CoalesceThreshold = ct
		r := runArm("", cfg, m, reqs)
		coalPrec := 1.0
		if r.st.Coalesced > 0 {
			coalPrec = 1 - float64(r.st.CoalescedWrong)/float64(r.st.Coalesced)
		}
		crows = append(crows, []string{
			report.F3(ct), report.N(r.st.Backend), report.N(r.st.Coalesced),
			report.N(r.st.CoalescedWrong), report.Pct(coalPrec),
			report.Pct(r.st.CacheReportedPrecision()),
		})
	}
	w.Table([]string{"coalescing threshold", "backend calls", "coalesced",
		"coalesced WRONG", "precision of the coalescer",
		"precision the cache reports"}, crows)

	w.Found(
		"At the default 0.60, semantic coalescing saved",
		report.N(arms[0].st.Backend-sem.st.Backend), "backend calls and served",
		report.N(sem.st.CoalescedWrong), "wrong answers to do it. Loosen the knob and",
		"the coalescer's own precision falls away while **the number on the cache",
		"dashboard barely moves, because every one of those requests was a cache MISS**",
		"- the cache was asked, answered honestly, and is not implicated.",
		"Caching the coalesced answer, which is what a naive implementation does",
		"because it has a query and an answer in hand, converts",
		report.N(arms[3].st.Poisoned), "transient mistakes into permanent entries.",
		"The general form: **any component that can return another request's answer is",
		"a cache and needs a cache's metrics**, whatever the package it lives in.",
	)

	w.Sub("The concurrency half, for real")
	w.Note(
		"The policy above is measured on a virtual clock so the numbers are reproducible.",
		"The mechanism is a real streaming single-flight (`internal/flight`) and is",
		"exercised as one. Here it is under an actual herd of goroutines:",
	)
	w.Code(liveFlightDemo())
	w.Note(
		"Two properties there are not the textbook ones. The work is owned by the GROUP,",
		"not by the first caller, so the leader abandoning does not fail everyone waiting",
		"behind it - and under a herd the first caller is precisely the one who has been",
		"waiting longest and is likeliest to have given up. And a subscriber that arrives",
		"mid-stream is replayed the prefix, because a late joiner silently receiving a",
		"truncated answer is worse than an error.",
	)
}

func liveFlightDemo() string {
	var b strings.Builder
	g := flight.New()
	const herd = 32

	// Determinism here has to be built, not assumed. `Do` launches the leader's work
	// in a goroutine, so without a gate that goroutine races the loop below that is
	// still registering the other 31 subscribers -- and a follower counts as a LATE
	// joiner precisely when it arrives after the first chunk. The race is silent: it
	// changes only a number in a report, so it reads as a plausible result rather
	// than as a bug. It surfaced when the suite ran the report with GOMAXPROCS=8 left
	// over from the stress stage and late joiners went from 1 to 18.
	//
	// So: `herdReady` holds the leader before its first emit until the whole herd is
	// subscribed, and `started` holds the explicit late joiner until after it. Every
	// ordering the counters depend on is now a happens-before edge, not a scheduling
	// accident.
	herdReady := make(chan struct{})
	started := make(chan struct{})
	rest := make(chan struct{})
	work := func(ctx context.Context, emit flight.Emit) error {
		<-herdReady
		emit([]byte("the "))
		emit([]byte("refund "))
		close(started)
		<-rest
		emit([]byte("window "))
		emit([]byte("is "))
		emit([]byte("30 days"))
		return nil
	}

	subs := make([]*flight.Sub, herd)
	for i := range subs {
		subs[i], _ = g.Do(context.Background(), "same-question", work)
	}
	close(herdReady)
	<-started
	late, _ := g.Do(context.Background(), "same-question", work)
	close(rest)

	bodies := map[string]int{}
	for _, s := range append(subs, late) {
		body, _ := drain(s)
		bodies[body]++
		s.Close()
	}

	st := g.Stats()
	fmt.Fprintf(&b, "%d concurrent requests for the same question\n", herd+1)
	fmt.Fprintf(&b, "  backend calls            : %d\n", st.Calls)
	fmt.Fprintf(&b, "  leaders                  : %d\n", st.Leaders)
	fmt.Fprintf(&b, "  followers                : %d\n", st.Followers)
	fmt.Fprintf(&b, "  late joiners (mid-stream): %d\n", st.LateJoins)
	fmt.Fprintf(&b, "  distinct bodies received : %d\n", len(bodies))
	keys := make([]string, 0, len(bodies))
	for k := range bodies {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, body := range keys {
		fmt.Fprintf(&b, "    %2d x %q\n", bodies[body], body)
	}
	fmt.Fprintf(&b, "  leaders + followers == requests: %v\n",
		st.Leaders+st.Followers == herd+1)
	return b.String()
}

// --- 7. the summary ---------------------------------------------------------

func s7(w *report.W) {
	w.Section(7, "What to take away")
	w.Note(
		"1. **An aggregate false-hit rate on a semantic cache is close to meaningless.**",
		"97% of query pairs are trivially unrelated, so the aggregate is dominated by",
		"the easy case. Report the error rate on the confusable subset or report nothing.",
	)
	w.Note(
		"2. **The failure is structural, not a weak encoder.** Pooling bounds how far one",
		"token can move the vector. Swapping *germany* for *france* cannot cost more",
		"similarity than *germany*'s share of the sentence's mass, and that share is small.",
		"A better encoder shifts the numbers; the bound survives.",
	)
	w.Note(
		"3. **So fix it outside the similarity function.** A rare-token veto is",
		"length-insensitive by construction and can overrule a high cosine. This is the",
		"transferable idea: when one feature must be able to veto a decision, it cannot",
		"be a term in a weighted mean.",
	)
	w.Note(
		"4. **Coalescing is a cache, and it is a cache with no metrics.** Every semantic",
		"merge of two in-flight requests is a cache hit that the cache never sees and",
		"never counts. If you coalesce on similarity, your false-hit dashboard is",
		"measuring a subset of your false hits and telling you it is all of them.",
	)
	w.Note(
		"5. **Isolation is the one property similarity cannot express.** Three tenants",
		"asking a byte-identical question and needing three different answers is not a",
		"hard NLP problem; it is a problem that NLP is the wrong tool for. Scope",
		"structurally and pay the hit rate.",
	)
}

// drain reads a subscriber to completion, exactly as a caller would.
func drain(s *flight.Sub) (string, error) {
	var b strings.Builder
	for c := range s.Chunks() {
		if c.Done {
			return b.String(), c.Err
		}
		b.Write(c.Data)
	}
	return b.String(), nil
}
