import type { CaseStudy } from "./types";
import generatedCaseStudies from "./case-studies.json" with { type: "json" };

// Generated by `npm run sync` (scripts/sync-projects.mjs) from the curated
// source in case-studies.source.json, with evidence/ownership paths resolved
// to GitHub blob/tree URLs. Do not hand-edit case-studies.json.
export const caseStudies: CaseStudy[] = generatedCaseStudies;
