import type { Project, Track } from "./types";
import generatedProjects from "./projects.json" with { type: "json" };

// Generated by `npm run sync` (scripts/sync-projects.mjs) from tracked
// repository source (docs/catalogue.json, project READMEs/docs) plus the
// curated inputs in project-summaries.json. Do not hand-edit projects.json.
function parseTrack(value: string): Track {
  if (value === "foundation" || value === "dotnet-azure-modernization" || value === "ai-application-engineering") return value;
  throw new Error(`Unknown project track: ${value}`);
}

export const projects: Project[] = generatedProjects.map((project) => ({
  ...project,
  track: parseTrack(project.track),
}));

export const featuredProjects: Project[] = projects.filter((project) => project.featured);

export const tracks: { id: Track; label: string; description: string }[] = [
  {
    id: "foundation",
    label: "Product & service foundations",
    description:
      "Backend and platform reference systems: payments, ledgers, scheduling, identity and data platforms built as self-directed studies.",
  },
  {
    id: "dotnet-azure-modernization",
    label: ".NET & Azure modernization",
    description:
      "Legacy-to-modern migration mechanics: interop boundaries, strangler routing, saga verification and cutover tooling, studied in controlled environments.",
  },
  {
    id: "ai-application-engineering",
    label: "AI application engineering",
    description:
      "Applied AI systems work: retrieval evaluation, agent runtimes, evaluation harnesses and observability, measured with offline or simulated data.",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}
