#Requires -Version 5.1
<#
.SYNOPSIS
    Runs the strangler router experiment end to end.
.PARAMETER Save
    Also write the output to docs/results.md.
#>
param([switch]$Save)

$ErrorActionPreference = 'Stop'
$env:GOROOT = 'C:\Users\rukwaropaul\toolchains\go'
$env:GOPATH = 'C:\Users\rukwaropaul\go'
$env:GOPROXY = 'off'
$env:PATH = "$env:GOROOT\bin;$env:PATH"

Push-Location $PSScriptRoot
try {
    if ($Save) {
        $out = Join-Path $PSScriptRoot 'docs\results.md'
        New-Item -ItemType Directory -Force -Path (Split-Path $out) | Out-Null
        $header = @(
            '# Measured results',
            '',
            'Generated by ``.\demo.ps1 -Save``. Every number below is produced by',
            '``cmd/strangler`` from a deterministic corpus (seed 20240612), so this file',
            'reproduces exactly.',
            '',
            '```text'
        )
        Set-Content -Path $out -Value $header -Encoding utf8
        & go run ./cmd/strangler | Add-Content -Path $out -Encoding utf8
        if ($LASTEXITCODE -ne 0) { throw 'experiment failed' }
        Add-Content -Path $out -Value '```' -Encoding utf8
        Write-Host "wrote $out" -ForegroundColor Green
    }
    else {
        & go run ./cmd/strangler
        if ($LASTEXITCODE -ne 0) { throw 'experiment failed' }
    }
}
finally {
    Pop-Location
}
