param([switch]$Save)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot
$py = "C:\Users\rukwaropaul\AppData\Local\Programs\Python\Python312\python.exe"
if (-not (Test-Path $py)) { $py = "python" }

if ($Save) {
    New-Item -ItemType Directory -Force -Path docs | Out-Null
    $header = @(
        "# Measured results",
        "",
        '_Generated by `demo.py`. Every corpus is a pure function of its seed, so',
        "these numbers reproduce exactly._",
        "",
        '```'
    )
    $header | Set-Content -Encoding utf8 docs/results.md
    & $py demo.py | Add-Content -Encoding utf8 docs/results.md
    '```' | Add-Content -Encoding utf8 docs/results.md
    Write-Host "wrote docs/results.md"
} else {
    & $py demo.py
}
