// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SavannaLogistics.Infrastructure;

#nullable disable

namespace SavannaLogistics.Infrastructure.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    [Migration("20260902224110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SavannaLogistics.Domain.AlertRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("TripId");

                    b.HasIndex("Type", "AcknowledgedAt");

                    b.HasIndex("VehicleId", "OccurredAt");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.DeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FailedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FailedAt");

                    b.HasIndex("VehicleId");

                    b.ToTable("DeadLetters", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneAlias")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LicenceNumber")
                        .IsUnique();

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.EtaPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AbsoluteErrorSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("ActualArrival")
                        .HasColumnType("TEXT");

                    b.Property<long>("CalculatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EffectiveSpeedKph")
                        .HasColumnType("REAL");

                    b.Property<long>("PredictedArrival")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RemainingDistanceKm")
                        .HasColumnType("REAL");

                    b.Property<Guid>("TargetStopId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TripId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetStopId");

                    b.HasIndex("TripId", "TargetStopId");

                    b.HasIndex("VehicleId", "CalculatedAt");

                    b.ToTable("EtaPredictions", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.Geofence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CenterLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("CenterLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolygonJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RadiusKm")
                        .HasColumnType("REAL");

                    b.Property<int>("Shape")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Geofences", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.LateArrival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PingId");

                    b.HasIndex("VehicleId", "SequenceNumber");

                    b.ToTable("LateArrivals", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.RoutePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolylineJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DwellMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "Sequence")
                        .IsUnique();

                    b.ToTable("RouteStops", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActualCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActualStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStopSequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastArrivalAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastDepartureAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlannedStart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SlaDueAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("VehicleId", "Status");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CapacityCubicMetres")
                        .HasColumnType("REAL");

                    b.Property<double>("CapacityKg")
                        .HasColumnType("REAL");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDriverId");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.VehiclePing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("DeviceTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FuelPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("HeadingDegrees")
                        .HasColumnType("REAL");

                    b.Property<bool>("Ignition")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IngestTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("OdometerKm")
                        .HasColumnType("REAL");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpeedKph")
                        .HasColumnType("REAL");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTimestamp");

                    b.HasIndex("VehicleId", "DeviceTimestamp");

                    b.HasIndex("VehicleId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("VehiclePings", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.VehicleState", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentTripId")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("HeadingDegrees")
                        .HasColumnType("REAL");

                    b.Property<bool>("Ignition")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("OdometerKm")
                        .HasColumnType("REAL");

                    b.Property<double>("SpeedKph")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("Status");

                    b.ToTable("VehicleStates", (string)null);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.AlertRecord", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SavannaLogistics.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavannaLogistics.Domain.DeadLetter", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavannaLogistics.Domain.EtaPrediction", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.RouteStop", null)
                        .WithMany()
                        .HasForeignKey("TargetStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SavannaLogistics.Domain.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavannaLogistics.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavannaLogistics.Domain.LateArrival", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.VehiclePing", null)
                        .WithMany()
                        .HasForeignKey("PingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavannaLogistics.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavannaLogistics.Domain.RouteStop", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.RoutePlan", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavannaLogistics.Domain.Trip", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.RoutePlan", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SavannaLogistics.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SavannaLogistics.Domain.Vehicle", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.Driver", null)
                        .WithMany()
                        .HasForeignKey("AssignedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SavannaLogistics.Domain.VehiclePing", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SavannaLogistics.Domain.VehicleState", b =>
                {
                    b.HasOne("SavannaLogistics.Domain.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("SavannaLogistics.Domain.VehicleState", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
